/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prg_381_project;
import prg_381_project.model.Cleaner;
import prg_381_project.daoimpl.CleanerDAOImpl;
import prg_381_project.model.Supplier;
import prg_381_project.daoimpl.SupplierDAOImpl;
/**
 *
 * @author marcu
 */
public class Cleaners_Suppliers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cleaners_Suppliers.class.getName());

    /**
     * Creates new form Cleaners_Suppliers
     */
    public Cleaners_Suppliers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public String idText;
    public String cl_Name;
    public String cl_Surname;
    public String cl_Department;
    public String supp_supplierId;
    public String supp_name;
    public String supp_phone;
    public String supp_email;
    public String supp_address;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab_Index = new javax.swing.JTabbedPane();
        Cleaner_Tab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cl_Delete = new javax.swing.JButton();
        Cleaner_Department = new javax.swing.JTextField();
        Cleaner_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cl_Add = new javax.swing.JButton();
        cl_Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Cleaner_Surname1 = new javax.swing.JTextField();
        Cleaner_Name1 = new javax.swing.JTextField();
        Supplier_Tab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Supplier_ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Supplier_Email = new javax.swing.JTextField();
        supp_Add = new javax.swing.JButton();
        supp_Delete = new javax.swing.JButton();
        supp_Update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Supplier_Phone = new javax.swing.JTextField();
        Supplier_Address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Supplier_Name1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab_Index.setBackground(new java.awt.Color(102, 102, 102));
        Tab_Index.setForeground(new java.awt.Color(255, 255, 255));
        Tab_Index.setName("C_S"); // NOI18N

        Cleaner_Tab.setBackground(new java.awt.Color(51, 51, 51));
        Cleaner_Tab.setForeground(new java.awt.Color(255, 255, 255));
        Cleaner_Tab.setFocusTraversalPolicyProvider(true);
        Cleaner_Tab.setName("Cleaners"); // NOI18N
        Cleaner_Tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Cleaner Department");
        Cleaner_Tab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 20));
        jLabel1.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel2.setText("CleanerID");
        Cleaner_Tab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        cl_Delete.setText("Delete");
        cl_Delete.addActionListener(this::cl_DeleteActionPerformed);
        Cleaner_Tab.add(cl_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 220, 40));

        Cleaner_Department.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_Department.setName("SName"); // NOI18N
        Cleaner_Tab.add(Cleaner_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 20));

        Cleaner_ID.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_ID.setName("SName"); // NOI18N
        Cleaner_Tab.add(Cleaner_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 20));
        Cleaner_ID.getAccessibleContext().setAccessibleName("Cleaner_ID");
        Cleaner_ID.getAccessibleContext().setAccessibleParent(null);

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel3.setText("Cleaner Name");
        Cleaner_Tab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, 20));

        cl_Add.setText("ADD");
        cl_Add.addActionListener(this::cl_AddActionPerformed);
        Cleaner_Tab.add(cl_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 220, 40));

        cl_Update.setText("Update Info");
        cl_Update.addActionListener(this::cl_UpdateActionPerformed);
        Cleaner_Tab.add(cl_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 220, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Cleaner_Tab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 390, 250));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel7.setText("Cleaner Surname");
        Cleaner_Tab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 20));

        Cleaner_Surname1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_Surname1.setName("SName"); // NOI18N
        Cleaner_Tab.add(Cleaner_Surname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, 20));

        Cleaner_Name1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_Name1.setName("SName"); // NOI18N
        Cleaner_Tab.add(Cleaner_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 20));

        Tab_Index.addTab("Cleaners", Cleaner_Tab);
        Cleaner_Tab.getAccessibleContext().setAccessibleName("");

        Supplier_Tab.setBackground(new java.awt.Color(51, 51, 51));
        Supplier_Tab.setForeground(new java.awt.Color(255, 255, 255));
        Supplier_Tab.setName("Suppliers"); // NOI18N
        Supplier_Tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel4.setText("SupplierID");
        Supplier_Tab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        Supplier_ID.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_ID.setName("SName"); // NOI18N
        Supplier_Tab.add(Supplier_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 20));
        Supplier_ID.getAccessibleContext().setAccessibleName("Supplier_ID");
        Supplier_ID.getAccessibleContext().setAccessibleParent(null);

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel5.setText("Supplier Name");
        Supplier_Tab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 20));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel6.setText("Supplier Address");
        Supplier_Tab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 20));

        Supplier_Email.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_Email.setName("SName"); // NOI18N
        Supplier_Tab.add(Supplier_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 220, 20));
        Supplier_Email.getAccessibleContext().setAccessibleName("Supplier_Email");
        Supplier_Email.getAccessibleContext().setAccessibleParent(null);

        supp_Add.setText("ADD");
        supp_Add.addActionListener(this::supp_AddActionPerformed);
        Supplier_Tab.add(supp_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, 40));

        supp_Delete.setText("Delete");
        supp_Delete.addActionListener(this::supp_DeleteActionPerformed);
        Supplier_Tab.add(supp_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 220, 40));

        supp_Update.setText("Update Info");
        supp_Update.addActionListener(this::supp_UpdateActionPerformed);
        Supplier_Tab.add(supp_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 220, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Supplier_Tab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 410, 300));

        Supplier_Phone.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_Phone.setName("SName"); // NOI18N
        Supplier_Tab.add(Supplier_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, 20));
        Supplier_Phone.getAccessibleContext().setAccessibleName("Supplier_Phone");
        Supplier_Phone.getAccessibleContext().setAccessibleDescription("");
        Supplier_Phone.getAccessibleContext().setAccessibleParent(null);

        Supplier_Address.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_Address.setName("SName"); // NOI18N
        Supplier_Tab.add(Supplier_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 20));
        Supplier_Address.getAccessibleContext().setAccessibleName("Supplier_Address");
        Supplier_Address.getAccessibleContext().setAccessibleParent(null);

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel8.setText("Supplier Phone");
        Supplier_Tab.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, 20));

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel9.setText("Supplier Email");
        Supplier_Tab.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 20));

        Supplier_Name1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_Name1.setName("SName"); // NOI18N
        Supplier_Tab.add(Supplier_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 220, 20));

        Tab_Index.addTab("Suppliers", Supplier_Tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Tab_Index, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab_Index, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab_Index.getAccessibleContext().setAccessibleName("Cleaners");

        getAccessibleContext().setAccessibleName("C_S");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void CLDetails(){
           idText = Cleaner_ID.getText().trim();
           cl_Name = Cleaner_Name1.getText().trim();
           cl_Surname = Cleaner_Surname1.getText().trim();
           cl_Department = Cleaner_Department.getText().trim();

            if (idText.isEmpty() || cl_Name.isEmpty() || cl_Surname.isEmpty() || cl_Department.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please fill in all fields before adding a cleaner.", 
                    "Validation Error", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return; // Stop execution
                }   
        }
        public void SuppDetails(){
            supp_supplierId = Supplier_ID.getText().trim();
            supp_name = Supplier_Name1.getText().trim();
            supp_phone = Supplier_Phone.getText().trim();
            supp_email = Supplier_Email.getText().trim();
            supp_address = Supplier_Address.getText().trim();

             if (idText.isEmpty() || cl_Name.isEmpty() || cl_Surname.isEmpty() || cl_Department.isEmpty()) {
                 javax.swing.JOptionPane.showMessageDialog(this, 
                     "Please fill in all fields before adding a cleaner.", 
                     "Validation Error", 
                     javax.swing.JOptionPane.WARNING_MESSAGE);
                 return; // Stop execution
                 }   
        }  
    private void cl_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_DeleteActionPerformed
         
        CLDetails();
       try {
            int cl_ID = Integer.parseInt(idText);
            CleanerDAOImpl cleanerDAO = new CleanerDAOImpl(); 
            boolean isAdded = cleanerDAO.deleteCleaner(cl_ID); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cleaner updated successfully!");

                // Clear input fields after success
                Cleaner_ID.setText("");
                Cleaner_Name1.setText("");
                Cleaner_Surname1.setText("");
                Cleaner_Department.setText("");      
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cleaner ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cl_DeleteActionPerformed

    private void cl_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_AddActionPerformed
        // TODO add your handling code here:
        
           CLDetails(); 

            try {
            int cl_ID = Integer.parseInt(idText);

            Cleaner cleaner = new Cleaner(cl_ID, cl_Name, cl_Surname, cl_Department);
            CleanerDAOImpl cleanerDAO = new CleanerDAOImpl(); 
            boolean isAdded = cleanerDAO.addCleaner(cleaner); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cleaner added successfully!");

                // Clear input fields after success
                Cleaner_ID.setText("");
                Cleaner_Name1.setText("");
                Cleaner_Surname1.setText("");
                Cleaner_Department.setText("");      
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cleaner ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cl_AddActionPerformed

    private void cl_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_UpdateActionPerformed
        // TODO add your handling code here:
        CLDetails();
               
       try {
            int cl_ID = Integer.parseInt(idText);

            Cleaner cleaner = new Cleaner(cl_ID, cl_Name, cl_Surname, cl_Department);
            CleanerDAOImpl cleanerDAO = new CleanerDAOImpl(); 
            boolean isAdded = cleanerDAO.updateCleaner(cleaner); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cleaner updated successfully!");

                // Clear input fields after success
                Cleaner_ID.setText("");
                Cleaner_Name1.setText("");
                Cleaner_Surname1.setText("");
                Cleaner_Department.setText("");      
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cleaner ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cl_UpdateActionPerformed

    private void supp_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_AddActionPerformed
        // TODO add your handling code here:
        SuppDetails();
        
        
        try {
            int supp_ID = Integer.parseInt(supp_supplierId);

            Supplier supplier = new Supplier(supp_ID, supp_name, supp_phone, supp_email,supp_address);
            SupplierDAOImpl supplierDAO = new SupplierDAOImpl(); 
            boolean isAdded = supplierDAO.addSupplier(supplier); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Supplier added successfully!");

                // Clear input fields after success
                Supplier_ID.setText("");
                Supplier_Name1.setText("");
                Supplier_Phone.setText("");
                Supplier_Email.setText("");
                Supplier_Address.setText("");
               
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Supplier ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_supp_AddActionPerformed

    private void supp_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_DeleteActionPerformed
        // TODO add your handling code here:
        SuppDetails();
        
        
        try {
            int supp_ID = Integer.parseInt(supp_supplierId);

            SupplierDAOImpl supplierDAO = new SupplierDAOImpl(); 
            boolean isAdded = supplierDAO.deleteSupplier(supp_ID); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Supplier deleted successfully!");

                // Clear input fields after success
                Supplier_ID.setText("");
                Supplier_Name1.setText("");
                Supplier_Phone.setText("");
                Supplier_Email.setText("");
                Supplier_Address.setText("");
               
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Supplier ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_supp_DeleteActionPerformed

    private void supp_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_UpdateActionPerformed
            // TODO add your handling code here:
            SuppDetails();
        
        
        try {
            int supp_ID = Integer.parseInt(supp_supplierId);

            Supplier supplier = new Supplier(supp_ID, supp_name, supp_phone, supp_email,supp_address);
            SupplierDAOImpl supplierDAO = new SupplierDAOImpl(); 
            boolean isAdded = supplierDAO.updateSupplier(supplier); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Supplier updated successfully!");

                // Clear input fields after success
                Supplier_ID.setText("");
                Supplier_Name1.setText("");
                Supplier_Phone.setText("");
                Supplier_Email.setText("");
                Supplier_Address.setText("");
               
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Supplier ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_supp_UpdateActionPerformed

    
    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTable1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cleaners_Suppliers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cleaner_Department;
    public javax.swing.JTextField Cleaner_ID;
    private javax.swing.JTextField Cleaner_Name1;
    private javax.swing.JTextField Cleaner_Surname1;
    private javax.swing.JPanel Cleaner_Tab;
    private javax.swing.JTextField Supplier_Address;
    private javax.swing.JTextField Supplier_Email;
    private javax.swing.JTextField Supplier_ID;
    private javax.swing.JTextField Supplier_Name1;
    private javax.swing.JTextField Supplier_Phone;
    private javax.swing.JPanel Supplier_Tab;
    private javax.swing.JTabbedPane Tab_Index;
    private javax.swing.JButton cl_Add;
    private javax.swing.JButton cl_Delete;
    private javax.swing.JButton cl_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton supp_Add;
    private javax.swing.JButton supp_Delete;
    private javax.swing.JButton supp_Update;
    // End of variables declaration//GEN-END:variables
}
