/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prg_381_project;
import prg_381_project.model.Cleaner;
import prg_381_project.daoimpl.CleanerDAOImpl;
/**
 *
 * @author marcu
 */
public class Cleaners_Suppliers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cleaners_Suppliers.class.getName());

    /**
     * Creates new form Cleaners_Suppliers
     */
    public Cleaners_Suppliers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab_Index = new javax.swing.JTabbedPane();
        Login_Tab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cl_Delete = new javax.swing.JButton();
        Cleaner_Department = new javax.swing.JTextField();
        Cleaner_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cl_Add = new javax.swing.JButton();
        cl_View = new javax.swing.JButton();
        cl_Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Cleaner_Surname1 = new javax.swing.JTextField();
        Cleaner_Name1 = new javax.swing.JTextField();
        Registration_Tab = new javax.swing.JPanel();
        javax.swing.JPasswordField Supplier_ID = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        Supplier_Name1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Supplier_Branch = new javax.swing.JTextField();
        supp_Add = new javax.swing.JButton();
        supp_View = new javax.swing.JButton();
        supp_Delete = new javax.swing.JButton();
        supp_Update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab_Index.setBackground(new java.awt.Color(102, 102, 102));
        Tab_Index.setForeground(new java.awt.Color(255, 255, 255));
        Tab_Index.setName("C_S"); // NOI18N

        Login_Tab.setBackground(new java.awt.Color(51, 51, 51));
        Login_Tab.setForeground(new java.awt.Color(255, 255, 255));
        Login_Tab.setFocusTraversalPolicyProvider(true);
        Login_Tab.setName("Cleaners"); // NOI18N
        Login_Tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Cleaner Department");
        Login_Tab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 20));
        jLabel1.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel2.setText("CleanerID");
        Login_Tab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        cl_Delete.setText("Delete");
        cl_Delete.addActionListener(this::cl_DeleteActionPerformed);
        Login_Tab.add(cl_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 220, 40));

        Cleaner_Department.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_Department.setName("SName"); // NOI18N
        Login_Tab.add(Cleaner_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 20));

        Cleaner_ID.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_ID.setName("SName"); // NOI18N
        Login_Tab.add(Cleaner_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 20));
        Cleaner_ID.getAccessibleContext().setAccessibleName("Cleaner_ID");
        Cleaner_ID.getAccessibleContext().setAccessibleParent(null);

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel3.setText("Cleaner Name");
        Login_Tab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, 20));

        cl_Add.setText("ADD");
        cl_Add.addActionListener(this::cl_AddActionPerformed);
        Login_Tab.add(cl_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 220, 40));

        cl_View.setText("View");
        cl_View.addActionListener(this::cl_ViewActionPerformed);
        Login_Tab.add(cl_View, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 220, 40));

        cl_Update.setText("Update Info");
        cl_Update.addActionListener(this::cl_UpdateActionPerformed);
        Login_Tab.add(cl_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 220, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Login_Tab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 390, 250));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel7.setText("Cleaner Surname");
        Login_Tab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 20));

        Cleaner_Surname1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_Surname1.setName("SName"); // NOI18N
        Login_Tab.add(Cleaner_Surname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, 20));

        Cleaner_Name1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Cleaner_Name1.setName("SName"); // NOI18N
        Login_Tab.add(Cleaner_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 20));

        Tab_Index.addTab("Cleaners", Login_Tab);
        Login_Tab.getAccessibleContext().setAccessibleName("");

        Registration_Tab.setBackground(new java.awt.Color(51, 51, 51));
        Registration_Tab.setForeground(new java.awt.Color(255, 255, 255));
        Registration_Tab.setName("Suppliers"); // NOI18N
        Registration_Tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Supplier_ID.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_ID.addActionListener(this::Supplier_IDActionPerformed);
        Registration_Tab.add(Supplier_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 50));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel4.setText("SupplierID");
        Registration_Tab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        Supplier_Name1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_Name1.setName("SName"); // NOI18N
        Registration_Tab.add(Supplier_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, 50));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel5.setText("Supplier Name");
        Registration_Tab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 20));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel6.setText("Supplier Branch");
        Registration_Tab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 20));

        Supplier_Branch.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Supplier_Branch.setName("SName"); // NOI18N
        Registration_Tab.add(Supplier_Branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 220, 50));
        Supplier_Branch.getAccessibleContext().setAccessibleName("Supplier Branch");

        supp_Add.setText("ADD");
        supp_Add.addActionListener(this::supp_AddActionPerformed);
        Registration_Tab.add(supp_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, 40));

        supp_View.setText("View");
        supp_View.addActionListener(this::supp_ViewActionPerformed);
        Registration_Tab.add(supp_View, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 220, 40));

        supp_Delete.setText("Delete");
        supp_Delete.addActionListener(this::supp_DeleteActionPerformed);
        Registration_Tab.add(supp_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 220, 40));

        supp_Update.setText("Update Info");
        supp_Update.addActionListener(this::supp_UpdateActionPerformed);
        Registration_Tab.add(supp_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 220, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Registration_Tab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 410, 300));

        Tab_Index.addTab("Suppliers", Registration_Tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Tab_Index, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab_Index, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab_Index.getAccessibleContext().setAccessibleName("Cleaners");

        getAccessibleContext().setAccessibleName("C_S");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cl_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_DeleteActionPerformed
        String idText = Cleaner_ID.getText().trim();
        String cl_Name = Cleaner_Name1.getText().trim();
        String cl_Surname = Cleaner_Surname1.getText().trim();
        String cl_Department = Cleaner_Department.getText().trim();

        if (idText.isEmpty() || cl_Name.isEmpty() || cl_Surname.isEmpty() || cl_Department.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please fill in all fields before adding a cleaner.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Stop execution
            }  
        
       try {
            int cl_ID = Integer.parseInt(idText);
            CleanerDAOImpl cleanerDAO = new CleanerDAOImpl(); 
            boolean isAdded = cleanerDAO.deleteCleaner(cl_ID); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cleaner updated successfully!");

                // Clear input fields after success
                Cleaner_ID.setText("");
                Cleaner_Name1.setText("");
                Cleaner_Surname1.setText("");
                Cleaner_Department.setText("");      
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cleaner ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cl_DeleteActionPerformed

    private void cl_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_AddActionPerformed
        // TODO add your handling code here:
        
            String idText = Cleaner_ID.getText().trim();
            String cl_Name = Cleaner_Name1.getText().trim();
            String cl_Surname = Cleaner_Surname1.getText().trim();
            String cl_Department = Cleaner_Department.getText().trim();

            if (idText.isEmpty() || cl_Name.isEmpty() || cl_Surname.isEmpty() || cl_Department.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please fill in all fields before adding a cleaner.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Stop execution
            }  

            try {
            int cl_ID = Integer.parseInt(idText);

            Cleaner cleaner = new Cleaner(cl_ID, cl_Name, cl_Surname, cl_Department);
            CleanerDAOImpl cleanerDAO = new CleanerDAOImpl(); 
            boolean isAdded = cleanerDAO.addCleaner(cleaner); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cleaner added successfully!");

                // Clear input fields after success
                Cleaner_ID.setText("");
                Cleaner_Name1.setText("");
                Cleaner_Surname1.setText("");
                Cleaner_Department.setText("");      
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cleaner ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cl_AddActionPerformed

    private void cl_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_ViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cl_ViewActionPerformed

    private void cl_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_UpdateActionPerformed
        // TODO add your handling code here:
        String idText = Cleaner_ID.getText().trim();
        String cl_Name = Cleaner_Name1.getText().trim();
        String cl_Surname = Cleaner_Surname1.getText().trim();
        String cl_Department = Cleaner_Department.getText().trim();

        if (idText.isEmpty() || cl_Name.isEmpty() || cl_Surname.isEmpty() || cl_Department.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please fill in all fields before adding a cleaner.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Stop execution
            }  
        
       try {
            int cl_ID = Integer.parseInt(idText);

            Cleaner cleaner = new Cleaner(cl_ID, cl_Name, cl_Surname, cl_Department);
            CleanerDAOImpl cleanerDAO = new CleanerDAOImpl(); 
            boolean isAdded = cleanerDAO.updateCleaner(cleaner); 

            if (isAdded) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cleaner updated successfully!");

                // Clear input fields after success
                Cleaner_ID.setText("");
                Cleaner_Name1.setText("");
                Cleaner_Surname1.setText("");
                Cleaner_Department.setText("");      
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add cleaner. Please try again.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cleaner ID must be a valid whole number.", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cl_UpdateActionPerformed

    private void supp_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_AddActionPerformed

    private void supp_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_ViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_ViewActionPerformed

    private void supp_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_DeleteActionPerformed

    private void supp_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_UpdateActionPerformed

    private void Supplier_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Supplier_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cleaners_Suppliers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cleaner_Department;
    public javax.swing.JTextField Cleaner_ID;
    private javax.swing.JTextField Cleaner_Name1;
    private javax.swing.JTextField Cleaner_Surname1;
    private javax.swing.JPanel Login_Tab;
    private javax.swing.JPanel Registration_Tab;
    private javax.swing.JTextField Supplier_Branch;
    private javax.swing.JTextField Supplier_Name1;
    private javax.swing.JTabbedPane Tab_Index;
    private javax.swing.JButton cl_Add;
    private javax.swing.JButton cl_Delete;
    private javax.swing.JButton cl_Update;
    private javax.swing.JButton cl_View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton supp_Add;
    private javax.swing.JButton supp_Delete;
    private javax.swing.JButton supp_Update;
    private javax.swing.JButton supp_View;
    // End of variables declaration//GEN-END:variables
}
